// <auto-generated />
using CIPP_API_ALT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIPP_API_ALT.Migrations.ExcludedTenants_Migrations
{
    [DbContext(typeof(ExcludedTenants))]
    partial class ExcludedTenantsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("CIPP_API_ALT.Data.ExcludedTenants+ExcludedTenant", b =>
                {
                    b.Property<string>("TenantDefaultDomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateString")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantDefaultDomain");

                    b.ToTable("_excludedTenantEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
