// <auto-generated />
using FFPP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FFPP.Migrations.ExcludedTenants_Migrations
{
    [DbContext(typeof(ExcludedTenants))]
    [Migration("20220808054850_InitialCreate_ExcludedTenants")]
    partial class InitialCreate_ExcludedTenants
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("FFPP.Data.ExcludedTenants+ExcludedTenant", b =>
                {
                    b.Property<string>("TenantDefaultDomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateString")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("TenantDefaultDomain");

                    b.ToTable("_excludedTenantEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
